//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextileResearchDevelopment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TextileResearchDevelopmentEntities : DbContext
    {
        public TextileResearchDevelopmentEntities()
            : base("name=TextileResearchDevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<YarnDyedRepeat> YarnDyedRepeats { get; set; }
        public virtual DbSet<YDView> YDViews { get; set; }
        public virtual DbSet<MasterReportView> MasterReportViews { get; set; }
    }
}
