//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextileResearchDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemarksView
    {
        public int Id { get; set; }
        public int TestReportID { get; set; }
        public long BarCode { get; set; }
        public int ReviseStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> AOPID { get; set; }
        public Nullable<decimal> FinalWidth { get; set; }
        public Nullable<decimal> FinalGSM { get; set; }
        public Nullable<decimal> TumbleLength { get; set; }
        public Nullable<decimal> TumbleWidth { get; set; }
        public Nullable<decimal> TumbleSP { get; set; }
        public string PrintName { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> StenterID { get; set; }
        public Nullable<int> PrintType { get; set; }
        public Nullable<int> MachineType { get; set; }
        public string SoftenerGL { get; set; }
        public string SoftenerName { get; set; }
        public Nullable<int> DyeingID { get; set; }
        public Nullable<decimal> GreyWidth { get; set; }
        public Nullable<decimal> GreyGSM { get; set; }
        public string YarnBrand { get; set; }
        public string YarnLot { get; set; }
        public string YarnCount { get; set; }
        public string KnitUnit { get; set; }
        public string McBrand { get; set; }
        public string Color { get; set; }
        public string OrderNo { get; set; }
        public string FabricName { get; set; }
        public string BuyerName { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string McDiaGauge { get; set; }
        public Nullable<int> FabricTypeID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<System.DateTime> FabricCreateTime { get; set; }
        public Nullable<int> DiaGaugeID { get; set; }
        public Nullable<int> YarnCountID { get; set; }
        public Nullable<int> KnitUnitID { get; set; }
        public Nullable<int> McBrandID { get; set; }
        public Nullable<int> KnitID { get; set; }
        public Nullable<int> FabricID { get; set; }
        public Nullable<int> DyeingUnitID { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string DyeingUnitName { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public string Peder { get; set; }
        public Nullable<decimal> Blower { get; set; }
        public Nullable<int> ApprovedStatus { get; set; }
        public string CreateByName { get; set; }
        public string UpdateByName { get; set; }
        public string ApprovedByName { get; set; }
        public Nullable<decimal> DIA { get; set; }
        public Nullable<decimal> GSM { get; set; }
        public Nullable<int> BatchQty { get; set; }
        public Nullable<decimal> WidthSet { get; set; }
        public Nullable<decimal> OverFeed { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
        public string Note { get; set; }
        public string LabdipStatus { get; set; }
        public Nullable<decimal> TumbleGSM { get; set; }
        public Nullable<int> MCRPM { get; set; }
        public Nullable<int> MCNO { get; set; }
        public Nullable<decimal> StitchLength { get; set; }
        public Nullable<int> RequiredGSM { get; set; }
        public string RequiredWidth { get; set; }
        public Nullable<decimal> TumbleWidthKnit { get; set; }
    }
}
