//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextileResearchDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportView
    {
        public int Id { get; set; }
        public int FabridID { get; set; }
        public int KnitID { get; set; }
        public int DyeingID { get; set; }
        public int StenterID { get; set; }
        public int AOPID { get; set; }
        public int TesReportID { get; set; }
        public int RemarksID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> CreateByKnit { get; set; }
        public Nullable<System.DateTime> CreateTimeKnit { get; set; }
        public Nullable<System.DateTime> UpdateTimeKnit { get; set; }
        public Nullable<int> UpdateByKnit { get; set; }
        public Nullable<System.DateTime> ApprovedTimeKnit { get; set; }
        public Nullable<int> ApprovedByKnit { get; set; }
        public Nullable<int> CreateByDyeing { get; set; }
        public Nullable<System.DateTime> UpdateTimeDyeing { get; set; }
        public Nullable<int> UpdateByDyeing { get; set; }
        public Nullable<System.DateTime> ApprovedTimeDyeing { get; set; }
        public Nullable<int> ApprovedByDyeing { get; set; }
        public Nullable<System.DateTime> CreateTimeDyeing { get; set; }
        public Nullable<System.DateTime> CreateTimeStenter { get; set; }
        public Nullable<int> CreateByStenter { get; set; }
        public Nullable<System.DateTime> UpdateTimeStenter { get; set; }
        public Nullable<int> UpdateByStenter { get; set; }
        public Nullable<System.DateTime> ApprovedTimeStenter { get; set; }
        public Nullable<int> ApprovedByStenter { get; set; }
        public Nullable<System.DateTime> CreateTimeAop { get; set; }
        public Nullable<int> CreateByAop { get; set; }
        public Nullable<System.DateTime> UpdateTimeAop { get; set; }
        public Nullable<int> UpdateByAop { get; set; }
        public Nullable<System.DateTime> ApprovedTimeAop { get; set; }
        public Nullable<int> ApprovedByAop { get; set; }
        public Nullable<System.DateTime> CreateTimeTest { get; set; }
        public Nullable<int> CreateByTest { get; set; }
        public Nullable<System.DateTime> UpdateTimeTest { get; set; }
        public Nullable<int> UpdateByTest { get; set; }
        public Nullable<System.DateTime> ApprovedTimeTest { get; set; }
        public Nullable<int> ApprovedByTest { get; set; }
        public Nullable<System.DateTime> CreateTimeRemarks { get; set; }
        public Nullable<int> CreateByRemarks { get; set; }
        public Nullable<System.DateTime> UpdateTimeRemarks { get; set; }
        public Nullable<int> UpdateByRemarks { get; set; }
        public Nullable<System.DateTime> ApprovedTimeRemarks { get; set; }
        public Nullable<int> ApprovedByRemarks { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<long> BarCode { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> FinalWidth { get; set; }
        public Nullable<decimal> FinalGSM { get; set; }
        public Nullable<decimal> TumbleLength { get; set; }
        public Nullable<decimal> TumbleWidth { get; set; }
        public Nullable<decimal> TumbleSP { get; set; }
        public string PrintName { get; set; }
        public string MachineName { get; set; }
        public Nullable<int> PrintType { get; set; }
        public Nullable<int> MachineType { get; set; }
        public string SoftenerGL { get; set; }
        public string SoftenerName { get; set; }
        public Nullable<decimal> GreyWidth { get; set; }
        public Nullable<decimal> GreyGSM { get; set; }
        public string YarnBrand { get; set; }
        public string YarnLot { get; set; }
        public string YarnCount { get; set; }
        public string KnitUnit { get; set; }
        public string McBrand { get; set; }
        public string Color { get; set; }
        public string OrderNo { get; set; }
        public string FabricName { get; set; }
        public string BuyerName { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string McDiaGauge { get; set; }
        public Nullable<int> DiaGaugeID { get; set; }
        public Nullable<int> YarnCountID { get; set; }
        public Nullable<int> KnitUnitID { get; set; }
        public Nullable<int> McBrandID { get; set; }
        public Nullable<int> DyeingUnitID { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string DyeingUnitName { get; set; }
        public Nullable<decimal> Temp { get; set; }
        public Nullable<decimal> Speed { get; set; }
        public string Peder { get; set; }
        public Nullable<decimal> Blower { get; set; }
        public Nullable<decimal> DIA { get; set; }
        public Nullable<decimal> GSM { get; set; }
        public Nullable<int> BatchQty { get; set; }
        public Nullable<decimal> WidthSet { get; set; }
        public Nullable<decimal> OverFeed { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
        public string Note { get; set; }
        public string LabdipStatus { get; set; }
        public Nullable<decimal> TumbleGSM { get; set; }
        public Nullable<int> MCRPM { get; set; }
        public Nullable<int> MCNO { get; set; }
        public Nullable<decimal> StitchLength { get; set; }
        public Nullable<int> RequiredGSM { get; set; }
        public string RequiredWidth { get; set; }
        public Nullable<decimal> TumbleWidthKnit { get; set; }
        public Nullable<int> FabricTypeID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> FabricID { get; set; }
    }
}
