//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextileResearchDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YarnDyedRepeat
    {
        public int Id { get; set; }
        public int KnitID { get; set; }
        public string YDRRepeat { get; set; }
        public string YDRColor { get; set; }
        public string YDRFeederNo { get; set; }
        public string YDRMeasurement { get; set; }
        public string YDRUOM { get; set; }
        public string YDRBatchNo { get; set; }
        public string YDRCK { get; set; }
    }
}
