//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextileResearchDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YDView
    {
        public int Id { get; set; }
        public int KnitID { get; set; }
        public int YDCountID { get; set; }
        public int YDCompositionID { get; set; }
        public int YDYarnTypeID { get; set; }
        public int YDYarnColorID { get; set; }
        public int YDSupplierID { get; set; }
        public string YarnCount { get; set; }
        public string YarnComposition { get; set; }
        public string YarnName { get; set; }
        public string YarnSupplier { get; set; }
        public string YarnColor { get; set; }
        public string Lot { get; set; }
        public string TPI { get; set; }
    }
}
